FROM opensuse/leap:15.2
WORKDIR /
RUN zypper install -y wget tar gzip
RUN wget https://github.com/Psy-Fer/interARTIC/releases/download/v0.4.4/interartic-v0.4.4-linux-x86-64-binaries.tar.gz -O interartic_bin.tar.gz
RUN tar xf interartic_bin.tar.gz
WORKDIR /interartic_bin
CMD ./run.sh -a 0.0.0.0
